"""Best-effort, on-disk-cached closed captions and scrub-bar thumbnails for
completed HDHomeRun DVR recordings.

Both are generated by running `ffmpeg` once against the whole recording file
and never regenerated after that — a completed recording is static, so the
first successful (or failed) attempt is final for that `recording_id`. Only
ever call these against a completed recording: an actively-growing DVR file
would produce an incomplete/wrong result.

Everything here degrades to `None` on any failure (missing ffmpeg, no
captions present, an unreachable URL) rather than raising — captions and
thumbnails are enhancements, not something a recording's playback should
ever fail over.
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
import math
import time
from pathlib import Path
from typing import Callable

from app.config import HDHOMERUN_MEDIA_CACHE_DIR
from app.dvr.builtin.tail_follow import pump_tail_follow

logger = logging.getLogger(__name__)

# Caption extraction decodes the whole file (no way to sample a prefix like
# the ffprobe detection pass does, since we don't know where in the
# recording captions will actually appear), at roughly 2 minutes of ffmpeg
# time per hour of content observed against real ATSC recordings - so this
# needs enough headroom for a multi-hour recording, not just a half-hour one.
_GENERATE_TIMEOUT_SECONDS = 600
_SPRITE_COLUMNS = 10
_SPRITE_ROWS = 10
_SPRITE_TILE_WIDTH = 160
_SPRITE_TILE_HEIGHT = 90
_MIN_SPRITE_INTERVAL_SECONDS = 2.0


def _cache_dir() -> Path:
    HDHOMERUN_MEDIA_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    return HDHOMERUN_MEDIA_CACHE_DIR


# Background live-caption extraction loops (see ensure_live_captions below),
# keyed by recording_id. capture_pipeline.stop_capture() calls
# stop_live_captions() as its single teardown choke point so a finished/
# torn-down capture never leaves an orphaned extraction loop running.
_live_caption_tasks: dict[str, asyncio.Task[None]] = {}


def stop_live_captions(recording_id: str) -> None:
    """Cancel the live-caption extraction loop for recording_id, if running."""
    task = _live_caption_tasks.pop(recording_id, None)
    if task and not task.done():
        task.cancel()


def _escape_movie_filter_url(url: str) -> str:
    """Escape a URL for use inside a quoted lavfi filtergraph argument.

    Single-quoting protects filtergraph-level syntax (commas, brackets,
    semicolons) but NOT colons - the `movie` filter's own per-filter option
    parser splits on the first unescaped `:` after the filename to find
    `:options`, even inside single quotes (e.g. an unescaped
    `http://host:port/...` gets truncated at the port's colon, and
    everything after it gets silently mis-parsed as filter options, so
    ffmpeg exits immediately with no video opened at all). So colons need
    their own backslash escape in addition to backslash/single-quote.
    """
    return url.replace("\\", "\\\\").replace("'", "\\'").replace(":", "\\:")


async def _run_ffmpeg(argv: list[str], timeout: float | None = None) -> bool:
    # Read _GENERATE_TIMEOUT_SECONDS from the module namespace at call time
    # (not as a default-argument value bound at def time) so tests can
    # monkeypatch it.
    if timeout is None:
        timeout = _GENERATE_TIMEOUT_SECONDS
    try:
        process = await asyncio.create_subprocess_exec(
            *argv,
            stdin=asyncio.subprocess.DEVNULL,
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.PIPE,
        )
    except OSError:
        return False

    try:
        await asyncio.wait_for(process.communicate(), timeout=timeout)
    except TimeoutError:
        process.kill()
        with contextlib.suppress(Exception):
            await process.wait()
        return False

    return process.returncode == 0


async def generate_captions_vtt(url: str, recording_id: str) -> Path | None:
    """The cached WebVTT captions file for `recording_id`, generating it first if needed.

    Returns None if extraction fails or the recording has no embedded
    CEA-608/708 captions - both look identical from here (ffmpeg exits 0
    either way when the source has no caption data, just with an
    effectively empty subtitle stream), so a missing/empty result is
    treated as "no captions" rather than surfaced as an error.
    """
    cache_path = _cache_dir() / f"{recording_id}.vtt"
    if cache_path.exists():
        return cache_path if cache_path.stat().st_size > 0 else None

    tmp_path = cache_path.with_suffix(".vtt.tmp")
    escaped_url = _escape_movie_filter_url(url)
    argv = [
        "ffmpeg",
        "-hide_banner",
        "-loglevel",
        "error",
        "-f",
        "lavfi",
        "-i",
        f"movie='{escaped_url}'[out+subcc]",
        "-map",
        "0:s:0",
        "-f",
        "webvtt",
        "-y",
        str(tmp_path),
    ]
    ok = await _run_ffmpeg(argv)
    if not ok:
        # A non-zero exit / timeout / missing binary isn't a confirmed
        # "no captions" result - it could be a slow/unreachable DVR, a
        # too-short timeout, or a transient ffmpeg crash - so don't cache
        # it as permanent failure. Only a *successful* ffmpeg run with an
        # empty result (below) means the source genuinely has no captions.
        with contextlib.suppress(FileNotFoundError):
            tmp_path.unlink()
        return None

    if not tmp_path.exists():
        cache_path.touch()
        return None

    tmp_path.replace(cache_path)
    return cache_path if cache_path.stat().st_size > 0 else None


# --- Real-time captions for in-progress recordings -------------------------
#
# generate_captions_vtt (above) decodes a whole, finished file in one
# continuous pass and is reliable specifically because of that continuity -
# the CEA-608/708 decoder inside ffmpeg's `movie` filter builds up roll-up-
# mode/PAC state as it goes and never has to guess.
#
# An earlier version of this ran a periodic windowed loop instead - spawning
# a brand-new ffmpeg process every few seconds, each one seeking cold into
# the middle of the growing file. Every fresh process started with no prior
# decoder state, which produced garbled/repeated text, dropped captions at
# window boundaries, and added latency from the segment cadence itself. This
# version instead runs a *single* long-lived ffmpeg process per active
# capture, started once from byte 0 with no seeking, fed the growing file
# continuously via pump_tail_follow (the same mechanism used for live
# recording playback), with its WebVTT stdout parsed incrementally as cues
# complete. If that process dies or hangs, it's restarted from byte 0 again
# (the only way to regain decoder continuity) and the output file is
# truncated and regenerated to match, rather than trying to dedup two
# separate decode passes against each other.

_LIVE_CAPTION_POLL_SECONDS = 2.0  # backoff between a dead/hung process and the next restart attempt
# Watchdog: a legitimately quiet caption stream (no dialogue) is normal and
# must not trigger a restart, so this only fires on total stdout silence,
# not "no cues" - if ffmpeg is genuinely still decoding, it stays responsive.
# A live source hiccup (tuner reconnect, signal dropout) can also stall the
# underlying capture file's growth for tens of seconds without
# pump_tail_follow giving up (it tolerates that indefinitely) - that alone
# would look identical to a hung ffmpeg process here, so this needs enough
# margin to not mistake one for the other. The cost of raising it is only a
# slower detection of a genuine hang, while the cost of it firing falsely is
# a full, possibly multi-minute re-decode from byte 0.
_LIVE_CAPTION_STDOUT_STALL_SECONDS = 60.0
_LIVE_CAPTION_TERMINATE_TIMEOUT_SECONDS = 5.0


def _live_caption_path(recording_id: str) -> Path:
    return _cache_dir() / f"{recording_id}.live.vtt"


def live_captions_path(recording_id: str) -> Path:
    """Where ensure_live_captions writes recording_id's growing captions
    file. Created (with just a WEBVTT header) as soon as the extraction loop
    starts - callers should still check .exists() since that only happens
    once the loop has actually been started via ensure_live_captions."""
    return _live_caption_path(recording_id)


def ensure_live_captions(
    recording_id: str,
    file_path: Path,
    is_source_alive: Callable[[], bool],
    capture_start_ts: float | None = None,
) -> None:
    """Lazily start the background live-caption extraction loop for
    recording_id if one isn't already running. Safe to call on every viewer's
    captions request - a no-op once the loop is already going."""
    if recording_id in _live_caption_tasks:
        return
    task = asyncio.create_task(
        _run_live_caption_loop(recording_id, file_path, is_source_alive, capture_start_ts)
    )
    _live_caption_tasks[recording_id] = task


def _reset_live_caption_output(output_path: Path) -> None:
    with contextlib.suppress(Exception):
        output_path.write_text("WEBVTT\n\n", encoding="utf-8")


async def _run_live_caption_loop(
    recording_id: str,
    file_path: Path,
    is_source_alive: Callable[[], bool],
    capture_start_ts: float | None = None,
) -> None:
    """Supervise the single long-lived captioning ffmpeg process for
    recording_id for the lifetime of the capture, restarting it (from byte 0
    again, with output truncated and regenerated) if it dies or hangs while
    the source is still alive."""
    output_path = _live_caption_path(recording_id)
    try:
        while is_source_alive():
            _reset_live_caption_output(output_path)
            should_restart = await _run_live_caption_process_once(
                file_path, output_path, is_source_alive, capture_start_ts
            )
            if should_restart and is_source_alive():
                elapsed = (
                    f"{time.time() - capture_start_ts:.0f}s into the capture"
                    if capture_start_ts is not None
                    else "unknown position in capture"
                )
                logger.warning(
                    "Live caption process restarting from byte 0 (%s) - full re-decode required", elapsed
                )
            if not should_restart or not is_source_alive():
                break
            await asyncio.sleep(_LIVE_CAPTION_POLL_SECONDS)
    except asyncio.CancelledError:
        raise
    finally:
        _live_caption_tasks.pop(recording_id, None)


async def _terminate_caption_process(process: asyncio.subprocess.Process) -> None:
    if process.returncode is not None:
        return
    process.terminate()
    try:
        await asyncio.wait_for(process.wait(), timeout=_LIVE_CAPTION_TERMINATE_TIMEOUT_SECONDS)
    except TimeoutError:
        process.kill()
        with contextlib.suppress(Exception):
            await process.wait()


async def _drain_stderr_logging(stream: asyncio.StreamReader) -> None:
    """Drain the caption ffmpeg process's stderr, logging anything it says.

    `-loglevel error` keeps this quiet in the normal case, so anything that
    arrives here is worth surfacing - it's the only visibility into *why* a
    given channel's captions come back empty (unsupported codec, no CC data,
    a probe failure on the pipe, etc.) instead of just silently producing
    nothing.
    """
    with contextlib.suppress(Exception):
        while True:
            chunk = await stream.read(4096)
            if not chunk:
                return
            text = chunk.decode("utf-8", errors="replace").strip()
            if text:
                logger.warning("Live caption ffmpeg stderr: %s", text)


async def _run_live_caption_process_once(
    file_path: Path,
    output_path: Path,
    is_source_alive: Callable[[], bool],
    capture_start_ts: float | None = None,
) -> bool:
    """Run one continuous captioning ffmpeg process, decoding file_path from
    byte 0 with no seeking, until the source dies, the process exits, or
    stdout goes silent for too long while the source is still alive (a hung
    process). Returns True if the caller should spawn a fresh attempt."""
    escaped_pipe = _escape_movie_filter_url("pipe:0")
    argv = [
        "ffmpeg",
        "-hide_banner",
        "-loglevel",
        "warning",
        "-f",
        "lavfi",
        "-i",
        f"movie='{escaped_pipe}':seek_point=0[out+subcc]",
        "-map",
        "0:s:0",
        "-f",
        "webvtt",
        "pipe:1",
    ]
    try:
        process = await asyncio.create_subprocess_exec(
            *argv,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
    except OSError:
        logger.warning("Could not start live caption ffmpeg process")
        return is_source_alive()

    assert process.stdin is not None
    assert process.stdout is not None
    assert process.stderr is not None

    pump_stop_event = asyncio.Event()
    pump_task = asyncio.create_task(
        pump_tail_follow(file_path, process.stdin, pump_stop_event, is_source_alive, start_offset_bytes=0)
    )
    drain_task = asyncio.create_task(_drain_stderr_logging(process.stderr))

    stalled = False

    async def stdout_reader() -> None:
        # Never let an exception here go unretrieved - this task is only
        # ever awaited on the cancellation path, so anything raised here
        # instead of returned/logged would otherwise surface as a
        # "Task exception was never retrieved" leak with no diagnostics.
        nonlocal stalled
        buffer = ""
        lag_samples: list[float] = []
        last_summary_monotonic = time.monotonic()

        def _record_lag_sample(lag: float) -> None:
            nonlocal last_summary_monotonic
            lag_samples.append(lag)
            now = time.monotonic()
            if now - last_summary_monotonic >= 30.0:
                logger.info(
                    "Live caption lag over last %.0fs: min=%.1fs avg=%.1fs max=%.1fs (n=%d)",
                    now - last_summary_monotonic,
                    min(lag_samples),
                    sum(lag_samples) / len(lag_samples),
                    max(lag_samples),
                    len(lag_samples),
                )
                lag_samples.clear()
                last_summary_monotonic = now

        try:
            while True:
                try:
                    chunk = await asyncio.wait_for(
                        process.stdout.read(4096), timeout=_LIVE_CAPTION_STDOUT_STALL_SECONDS
                    )
                except TimeoutError:
                    stalled = True
                    return
                if not chunk:
                    return
                buffer += chunk.decode("utf-8", errors="replace")
                while "\n\n" in buffer:
                    block, buffer = buffer.split("\n\n", 1)
                    cue = _parse_vtt_block(block)
                    if cue is not None:
                        _append_live_cues(output_path, [cue])
                        if capture_start_ts is not None:
                            lag = (time.time() - capture_start_ts) - cue[1]
                            logger.debug("Live caption cue appended: cue_end=%.1fs lag=%.1fs", cue[1], lag)
                            _record_lag_sample(lag)
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.warning("Live caption ffmpeg stdout reader failed", exc_info=True)

    reader_task = asyncio.create_task(stdout_reader())

    async def stop_pump_and_stdin() -> None:
        pump_stop_event.set()
        with contextlib.suppress(Exception):
            await pump_task
        with contextlib.suppress(Exception):
            process.stdin.close()

    try:
        await asyncio.wait({pump_task, reader_task}, return_when=asyncio.FIRST_COMPLETED)
    except asyncio.CancelledError:
        reader_task.cancel()
        with contextlib.suppress(Exception, asyncio.CancelledError):
            await stop_pump_and_stdin()
        with contextlib.suppress(Exception, asyncio.CancelledError):
            await reader_task
        await _terminate_caption_process(process)
        drain_task.cancel()
        raise

    # Whichever side finished first (source died, or ffmpeg exited/stalled on
    # its own), stop the other side and let ffmpeg wind down before reaping it.
    await stop_pump_and_stdin()
    if not reader_task.done():
        with contextlib.suppress(TimeoutError):
            await asyncio.wait_for(reader_task, timeout=_LIVE_CAPTION_TERMINATE_TIMEOUT_SECONDS)

    exit_code = process.returncode
    await _terminate_caption_process(process)
    drain_task.cancel()
    with contextlib.suppress(Exception, asyncio.CancelledError):
        await drain_task

    if stalled:
        logger.warning(
            "Live caption ffmpeg process stalled with no output for %.0fs", _LIVE_CAPTION_STDOUT_STALL_SECONDS
        )
    elif exit_code not in (0, None):
        logger.warning("Live caption ffmpeg process exited with code %s", exit_code)

    return is_source_alive()


def _parse_vtt_timestamp(raw: str) -> float:
    parts = raw.strip().split(":")
    if len(parts) == 3:
        return int(parts[0]) * 3600 + int(parts[1]) * 60 + float(parts[2])
    elif len(parts) == 2:
        return int(parts[0]) * 60 + float(parts[1])
    elif len(parts) == 1:
        return float(parts[0])
    return 0.0


def _parse_vtt_block(block: str) -> tuple[float, float, str] | None:
    """Parse a single WebVTT cue block (no leading/trailing blank lines).
    Returns None for a non-cue block (the WEBVTT header, or a block missing
    a `-->` timing line) or one with malformed timestamps."""
    lines = [line for line in block.split("\n") if line.strip()]
    cue_line_index = next((i for i, line in enumerate(lines) if "-->" in line), None)
    if cue_line_index is None:
        return None
    start_raw, end_raw = (part.strip() for part in lines[cue_line_index].split("-->")[:2])
    text_lines = lines[cue_line_index + 1 :]
    if not text_lines:
        return None
    try:
        start = _parse_vtt_timestamp(start_raw)
        end = _parse_vtt_timestamp(end_raw.split(" ")[0])
    except ValueError:
        return None
    return (start, end, "\n".join(text_lines))


def _parse_vtt_cues(text: str) -> list[tuple[float, float, str]]:
    cues: list[tuple[float, float, str]] = []
    for block in text.replace("\r\n", "\n").split("\n\n"):
        cue = _parse_vtt_block(block)
        if cue is not None:
            cues.append(cue)
    return cues


def _append_live_cues(output_path: Path, cues: list[tuple[float, float, str]]) -> None:
    is_new = not output_path.exists()
    lines: list[str] = []
    if is_new:
        lines.extend(["WEBVTT", ""])
    for start, end, text in cues:
        lines.append(f"{_format_timestamp(start)} --> {_format_timestamp(end)}")
        lines.append(text)
        lines.append("")
    with output_path.open("a") as f:
        f.write("\n".join(lines) + "\n")


def _sprite_paths(recording_id: str) -> tuple[Path, Path]:
    return _cache_dir() / f"{recording_id}.jpg", _cache_dir() / f"{recording_id}.thumbs.vtt"


def _format_timestamp(seconds: float) -> str:
    hours, remainder = divmod(max(0.0, seconds), 3600)
    minutes, secs = divmod(remainder, 60)
    return f"{int(hours):02d}:{int(minutes):02d}:{secs:06.3f}"


def _build_sprite_vtt(jpg_filename: str, interval_seconds: float, tile_count: int, grid_columns: int) -> str:
    lines = ["WEBVTT", ""]
    for index in range(tile_count):
        start = index * interval_seconds
        end = (index + 1) * interval_seconds
        col = index % grid_columns
        row = index // grid_columns
        x = col * _SPRITE_TILE_WIDTH
        y = row * _SPRITE_TILE_HEIGHT
        lines.append(f"{_format_timestamp(start)} --> {_format_timestamp(end)}")
        lines.append(f"{jpg_filename}#xywh={x},{y},{_SPRITE_TILE_WIDTH},{_SPRITE_TILE_HEIGHT}")
        lines.append("")
    return "\n".join(lines)


async def generate_thumbnail_sprite(url: str, recording_id: str, duration_seconds: float) -> tuple[Path, Path] | None:
    """The cached (sprite JPEG, cue VTT) pair for `recording_id`, generating first if needed.

    A single `_SPRITE_COLUMNS`x`_SPRITE_ROWS` grid is spread evenly across
    the whole recording (interval adapts to duration) rather than sampling
    at a fixed interval, so a long recording doesn't lose thumbnail
    coverage past the first few minutes.
    """
    jpg_path, vtt_path = _sprite_paths(recording_id)
    if jpg_path.exists() and vtt_path.exists():
        return jpg_path, vtt_path

    if duration_seconds <= 0:
        return None

    tile_count = _SPRITE_COLUMNS * _SPRITE_ROWS
    interval_seconds = max(_MIN_SPRITE_INTERVAL_SECONDS, duration_seconds / tile_count)
    actual_tile_count = min(tile_count, max(1, math.ceil(duration_seconds / interval_seconds)))

    # The tile filter's WxH area is sized for the worst case (a long
    # recording sampled down to the full grid). A short recording samples
    # far fewer frames than that, and the filter only ever emits an output
    # frame once it's buffered a full W*H input frames — so a fixed
    # _SPRITE_COLUMNS x _SPRITE_ROWS area would silently produce nothing for
    # anything shorter than that. Size the grid to what's actually sampled,
    # and cap nb_frames to the same count so the filter flushes as soon as
    # those frames arrive instead of waiting for a full grid.
    grid_columns = min(_SPRITE_COLUMNS, actual_tile_count)
    grid_rows = math.ceil(actual_tile_count / grid_columns)

    tmp_jpg = jpg_path.with_name(f"{jpg_path.name}.tmp")
    argv = [
        "ffmpeg",
        "-hide_banner",
        "-loglevel",
        "error",
        "-i",
        url,
        "-vf",
        (
            f"fps=1/{interval_seconds},scale={_SPRITE_TILE_WIDTH}:{_SPRITE_TILE_HEIGHT},"
            f"tile={grid_columns}x{grid_rows}:nb_frames={actual_tile_count}"
        ),
        "-frames:v",
        "1",
        "-q:v",
        "4",
        "-f",
        "image2",
        "-y",
        str(tmp_jpg),
    ]
    ok = await _run_ffmpeg(argv)
    if not ok or not tmp_jpg.exists():
        with contextlib.suppress(FileNotFoundError):
            tmp_jpg.unlink()
        return None

    tmp_jpg.replace(jpg_path)
    vtt_path.write_text(_build_sprite_vtt(jpg_path.name, interval_seconds, actual_tile_count, grid_columns))
    return jpg_path, vtt_path


def _poster_path(recording_id: str) -> Path:
    return _cache_dir() / f"{recording_id}.poster.jpg"


async def generate_poster(url: str, recording_id: str, offset_seconds: float = 10.0) -> Path | None:
    """Extract a representative snapshot frame from `url` for `recording_id`."""
    poster_path = _poster_path(recording_id)
    if poster_path.exists() and poster_path.stat().st_size > 0:
        return poster_path

    tmp_jpg = poster_path.with_name(f"{poster_path.name}.tmp")
    argv = [
        "ffmpeg",
        "-hide_banner",
        "-loglevel",
        "error",
        "-ss",
        str(offset_seconds),
        "-i",
        url,
        "-vf",
        "scale=640:-1",
        "-frames:v",
        "1",
        "-q:v",
        "3",
        "-f",
        "image2",
        "-y",
        str(tmp_jpg),
    ]
    ok = await _run_ffmpeg(argv, timeout=15)
    if not ok or not tmp_jpg.exists() or tmp_jpg.stat().st_size == 0:
        # Fallback to seeking from start (0s) if the offset was beyond duration
        argv_start = [
            "ffmpeg",
            "-hide_banner",
            "-loglevel",
            "error",
            "-ss",
            "0",
            "-i",
            url,
            "-vf",
            "scale=640:-1",
            "-frames:v",
            "1",
            "-q:v",
            "3",
            "-f",
            "image2",
            "-y",
            str(tmp_jpg),
        ]
        ok_start = await _run_ffmpeg(argv_start, timeout=15)
        if not ok_start or not tmp_jpg.exists() or tmp_jpg.stat().st_size == 0:
            with contextlib.suppress(FileNotFoundError):
                tmp_jpg.unlink()
            return None

    tmp_jpg.replace(poster_path)
    return poster_path if poster_path.exists() and poster_path.stat().st_size > 0 else None
