from __future__ import annotations

import pytest

from app import auth, config, crypto, hls_streaming, subprocess_streaming
from app.storage import db
from app.storage.cache import cache


@pytest.fixture(autouse=True)
def _reset_shared_state():
    """The TTL cache, PIN-login lockout tracker, and recent-stream-failure
    cache are process-wide singletons; tests must not leak cached values
    into each other."""
    cache._store.clear()
    auth._failed_attempts.clear()
    auth._ip_failed_attempts.clear()
    auth._last_sweep_at = 0.0
    subprocess_streaming._recent_stream_failures.clear()
    yield
    cache._store.clear()
    auth._failed_attempts.clear()
    auth._ip_failed_attempts.clear()
    auth._last_sweep_at = 0.0
    subprocess_streaming._recent_stream_failures.clear()


@pytest.fixture(autouse=True)
def _reset_ambient_settings(monkeypatch):
    """`app.config.settings` is a process-wide singleton loaded once from
    `.env` at import time. A developer's local `.env` commonly carries real
    provider API keys for manual testing, so tests must not see them —
    otherwise results (e.g. `has_<key>` flags) depend on whichever secrets
    happen to be configured on the machine running the suite."""
    for key in config.APP_SETTINGS_KEYS:
        monkeypatch.setattr(config.settings, key, config.Settings.model_fields[key].default, raising=False)


@pytest.fixture(autouse=True)
def _isolate_hls_session_dir(tmp_path, monkeypatch):
    """app.hls_streaming imports HLS_SESSION_DIR as a bound name (`from
    app.config import HLS_SESSION_DIR`), so isolating it requires patching
    hls_streaming.HLS_SESSION_DIR directly - patching config.HLS_SESSION_DIR
    would not be visible here. Autouse because a test that forgets to mock
    hls_streaming.allocate_session_dir() (this already happened once, see
    test_api_dvr_builtin.py's HLS tests) would otherwise create real
    directories under the real backend/hls_sessions/ on every run."""
    session_dir = tmp_path / "hls_sessions"
    session_dir.mkdir()
    monkeypatch.setattr(hls_streaming, "HLS_SESSION_DIR", session_dir)


@pytest.fixture
def tmp_db(tmp_path, monkeypatch):
    """Point app.storage.db at an isolated sqlite file for this test.

    Also isolates the secret-encryption key (app.crypto) to the same tmp
    dir — otherwise every test process would share (and create on disk) the
    real backend/secret.key file, and a key generated by one test run would
    silently make ciphertext from a previous run undecryptable.
    """
    db_path = tmp_path / "test.db"
    monkeypatch.setattr(db, "DB_PATH", db_path)
    monkeypatch.setattr(crypto, "SECRET_KEY_PATH", tmp_path / "secret.key")
    crypto.reset_key_cache()
    db.init_db()
    return db_path
