"""Whole-file closed captions for completed (static) DVR recordings.

Generated by running `ffmpeg` once against the whole recording file and
never regenerated after that - a completed recording is static, so the
first successful (or failed) attempt is final for that `recording_id`. Only
ever call this against a completed recording: an actively-growing DVR file
would produce an incomplete/wrong result.

Degrades to `None` on any failure (missing ffmpeg, no captions present, an
unreachable URL) rather than raising - captions are an enhancement, not
something a recording's playback should ever fail over.
"""

from __future__ import annotations

import asyncio
import contextlib
from pathlib import Path

from app.dvr.media.shared import _cache_dir, _run_ffmpeg, _strip_cc_control_artifacts


def _escape_movie_filter_url(url: str) -> str:
    """Escape a URL for use inside a quoted lavfi filtergraph argument.

    Single-quoting protects filtergraph-level syntax (commas, brackets,
    semicolons) but NOT colons - the `movie` filter's own per-filter option
    parser splits on the first unescaped `:` after the filename to find
    `:options`, even inside single quotes (e.g. an unescaped
    `http://host:port/...` gets truncated at the port's colon, and
    everything after it gets silently mis-parsed as filter options, so
    ffmpeg exits immediately with no video opened at all). So colons need
    their own backslash escape in addition to backslash/single-quote.
    """
    return url.replace("\\", "\\\\").replace("'", "\\'").replace(":", "\\:")


# Recording_id -> in-flight generate_captions_vtt() call, so a client's lazy
# on-request fetch and the eager post-recording trigger (see capture.py's
# stop_capture) never race each other into running ffmpeg twice against the
# same file.
_generate_captions_inflight: dict[str, asyncio.Task[Path | None]] = {}


async def generate_captions_vtt(url: str, recording_id: str) -> Path | None:
    """The cached WebVTT captions file for `recording_id`, generating it first if needed.

    Coalesces concurrent callers for the same recording_id (e.g. a client's
    on-request fetch racing the eager post-recording trigger) onto a single
    ffmpeg invocation rather than running it twice against the same file.
    """
    cache_path = _cache_dir() / f"{recording_id}.vtt"
    if cache_path.exists():
        return cache_path if cache_path.stat().st_size > 0 else None

    existing = _generate_captions_inflight.get(recording_id)
    if existing is not None:
        return await existing

    task = asyncio.create_task(_generate_captions_vtt_uncached(url, cache_path))
    _generate_captions_inflight[recording_id] = task
    try:
        return await task
    finally:
        _generate_captions_inflight.pop(recording_id, None)


async def _generate_captions_vtt_uncached(url: str, cache_path: Path) -> Path | None:
    """Returns None if extraction fails or the recording has no embedded
    CEA-608/708 captions - both look identical from here (ffmpeg exits 0
    either way when the source has no caption data, just with an
    effectively empty subtitle stream), so a missing/empty result is
    treated as "no captions" rather than surfaced as an error.
    """
    tmp_path = cache_path.with_suffix(".vtt.tmp")
    escaped_url = _escape_movie_filter_url(url)
    argv = [
        "ffmpeg",
        "-hide_banner",
        "-loglevel",
        "error",
        "-f",
        "lavfi",
        "-i",
        f"movie='{escaped_url}'[out+subcc]",
        "-map",
        "0:s:0",
        "-f",
        "webvtt",
        "-y",
        str(tmp_path),
    ]
    ok = await _run_ffmpeg(argv)
    if not ok:
        # A non-zero exit / timeout / missing binary isn't a confirmed
        # "no captions" result - it could be a slow/unreachable DVR, a
        # too-short timeout, or a transient ffmpeg crash - so don't cache
        # it as permanent failure. Only a *successful* ffmpeg run with an
        # empty result (below) means the source genuinely has no captions.
        with contextlib.suppress(FileNotFoundError):
            tmp_path.unlink()
        return None

    if not tmp_path.exists():
        cache_path.touch()
        return None

    raw_text = tmp_path.read_text(encoding="utf-8", errors="replace")
    cleaned_text = _strip_cc_control_artifacts(raw_text)
    if cleaned_text != raw_text:
        tmp_path.write_text(cleaned_text, encoding="utf-8")

    tmp_path.replace(cache_path)
    return cache_path if cache_path.stat().st_size > 0 else None
