"""SQLite persistence.

A plain, unpooled sqlite3 connection is enough here: this is a
single-backend, single-writer app (one household's HDHomeRun tuner), not a
multi-tenant service.

Split by domain across this package's submodules (connection/settings/users/
guide/recordings); this module re-exports the combined public API so
`from app.storage import db; db.func(...)` and `from app.storage.db import
func` both keep working exactly as they did when this was a single flat
file.
"""

from __future__ import annotations

from app.config import SECRET_APP_SETTINGS_KEYS

from .connection import (
    _MIGRATIONS,
    DB_PATH,
    _apply_migrations,
    _connect,
    _upsert,
    _validate_update_columns,
    init_db,
)
from .guide import (
    DEFAULT_GUIDE_PROVIDER_PRIORITY,
    delete_expired_sd_program_cache,
    delete_future_guide_programs,
    delete_guide_programs_by_provider,
    delete_sd_station_map,
    delete_xmltv_channel_map,
    get_cached_sd_programs,
    get_channel,
    get_channel_by_number,
    get_guide_provider_state,
    get_sd_station_map,
    get_xmltv_channel_map,
    get_xmltv_guide_stats,
    list_channels,
    list_guide_programs,
    list_sd_station_map,
    list_xmltv_channel_map,
    resolve_guide_programs,
    save_guide_provider_state,
    update_channel,
    upsert_channel,
    upsert_guide_programs,
    upsert_sd_program_cache,
    upsert_sd_station_map,
    upsert_xmltv_channel_map,
)
from .jobs import (
    create_job_run,
    finish_job_run,
    list_job_runs,
)
from .recordings import (
    create_recording,
    create_recording_rule,
    delete_recording,
    delete_recording_rule,
    delete_scheduled_recordings_for_rule,
    get_recording,
    get_recording_rule,
    list_completed_recordings,
    list_completed_recordings_by_title,
    list_recording_rules,
    list_recordings,
    list_scheduled_recordings,
    mark_in_progress_scheduled_recordings_interrupted,
    mark_scheduled_recording_in_progress,
    update_recording,
    update_recording_rule,
    update_scheduled_recording_status,
    upsert_scheduled_recording,
)
from .settings import (
    NETWORK_INTEGRATION_SECRET_KEYS,
    delete_network_integration,
    get_app_settings,
    get_network_integration,
    list_network_integrations,
    save_app_settings,
    save_network_integration,
)
from .users import (
    _DEFAULT_PREFERENCES,
    create_auth_token,
    create_session,
    create_user,
    delete_expired_sessions,
    delete_session,
    delete_sessions_for_user,
    delete_user,
    get_auth_token_by_hash,
    get_session,
    get_user,
    get_user_preferences,
    list_auth_tokens,
    list_users,
    revoke_auth_token,
    save_user_preferences,
    touch_auth_token,
    update_user,
)

__all__ = [
    "DB_PATH",
    "SECRET_APP_SETTINGS_KEYS",
    "NETWORK_INTEGRATION_SECRET_KEYS",
    "DEFAULT_GUIDE_PROVIDER_PRIORITY",
    # Underscore-prefixed but intentionally re-exported: existing tests do
    # white-box scaffolding against these (db._connect(), db._MIGRATIONS, ...).
    "_apply_migrations",
    "_connect",
    "_upsert",
    "_validate_update_columns",
    "_MIGRATIONS",
    "_DEFAULT_PREFERENCES",
    "init_db",
    "get_app_settings",
    "save_app_settings",
    "save_network_integration",
    "get_network_integration",
    "list_network_integrations",
    "delete_network_integration",
    "create_user",
    "get_user",
    "list_users",
    "update_user",
    "delete_user",
    "create_session",
    "get_session",
    "delete_session",
    "delete_sessions_for_user",
    "delete_expired_sessions",
    "create_auth_token",
    "get_auth_token_by_hash",
    "touch_auth_token",
    "list_auth_tokens",
    "revoke_auth_token",
    "get_user_preferences",
    "save_user_preferences",
    "upsert_channel",
    "list_channels",
    "get_channel",
    "get_channel_by_number",
    "update_channel",
    "upsert_guide_programs",
    "list_guide_programs",
    "delete_future_guide_programs",
    "delete_guide_programs_by_provider",
    "get_guide_provider_state",
    "save_guide_provider_state",
    "get_xmltv_guide_stats",
    "upsert_xmltv_channel_map",
    "get_xmltv_channel_map",
    "list_xmltv_channel_map",
    "delete_xmltv_channel_map",
    "upsert_sd_station_map",
    "get_sd_station_map",
    "list_sd_station_map",
    "delete_sd_station_map",
    "upsert_sd_program_cache",
    "get_cached_sd_programs",
    "delete_expired_sd_program_cache",
    "resolve_guide_programs",
    "create_recording_rule",
    "list_recording_rules",
    "get_recording_rule",
    "update_recording_rule",
    "delete_recording_rule",
    "upsert_scheduled_recording",
    "list_scheduled_recordings",
    "delete_scheduled_recordings_for_rule",
    "mark_scheduled_recording_in_progress",
    "update_scheduled_recording_status",
    "mark_in_progress_scheduled_recordings_interrupted",
    "create_recording",
    "update_recording",
    "list_recordings",
    "list_completed_recordings",
    "list_completed_recordings_by_title",
    "get_recording",
    "delete_recording",
    "create_job_run",
    "finish_job_run",
    "list_job_runs",
]
